apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-004730-i3wu-service
spec:
  selector:
    app: enterprise-system-004730-i3wu
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
